# Generated by Django 3.2.6 on 2022-01-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=70)),
                ('talktime', models.CharField(max_length=70)),
                ('data', models.CharField(max_length=70)),
                ('validity', models.CharField(max_length=70)),
                ('sms', models.CharField(max_length=70)),
                ('other_details', models.CharField(max_length=70, null=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_api.service_provider')),
            ],
        ),
    ]
