# Generated by Django 3.2.6 on 2022-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_api', '0003_alter_plan_other_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='data',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='other_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sms',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='talktime',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
